### PR TITLE
Activate tests

### PR DESCRIPTION
**Pull request by heiglandreas**
This is merely a test to check the PR #25 from @kevinpapst

### CODE REVIEW

**Comment by kevinpapst** [comment]
👍 

I could have done the testsuite split as well, I just wanted to get some feedback first and also I have no idea how to tell the Laminas CI system to only trigger the one suite by default. Do you?

**Comment by heiglandreas** [comment]
@kevinpapst: Feel free to grab the changed phpunit.xml.dist and add it to your PR :wink:

This was merely to do some testing on GHA. That was easier to setup that `act` :grin:

**Comment by kevinpapst** [comment]
I am totally happy about any help 👍 especially if you don't even need the changes right now!
And I don't care which PR or branch it happens in 😁 I just want to move forward and fix the issue.

**Comment by heiglandreas** [comment]
This can be closed as it has been superseeded by PR #29

**Pull request closed without merging**
