### PR TITLE
Add PHP 8.3 support

### LINKED ISSUE #46: PHP 8.3 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

The PHP dependency constraint is very strict, and doesn't allow new versions of PHP to be used as they come out:
`"php": "~8.0.0 || ~8.1.0 || ~8.2.0",`

Please either loosen this constraint so that people can use newer versions of PHP as they come out (e.g. `^8.0.0`), or else add official support for PHP 8.3 now that it has been released.

### PR DESCRIPTION
**Pull request by GuySartorelli**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

PHP 8.3 can't be used with this library due to the strict dependency constraint.
Loosening the constraint to allow new versions of PHP 8 to be automatically installable isn't allowed as per https://github.com/laminas/laminas-ldap/issues/46#issuecomment-1824889894, so I'm just adding PHP 8.3 support here.

I've checked against the changes listed in https://php.watch/versions/8.3 and none of the listed changes should break anything this library uses.

Hopefully your CI will automagically pick up that it needs to test against PHP 8.3 - but if not, please let me know what I need to change and I'll change it.

Closes #46

### CODE REVIEW

**Comment by Xerkus** [comment]
php 8.0 reached eol. Please also drop it and update platform to 8.1

**Comment by GuySartorelli** [comment]
.......... Okay. That's not at all in the scope of what I'm doing this change for, but if that's what has to be done for you to add PHP 8.3 support, I'll do it.

**Comment by GuySartorelli** [comment]
Done

**Comment by GuySartorelli** [comment]
Looks like there are some PHP 8.1 failures in CI - those are out of scope for this PR.

**Comment by Xerkus** [comment]
Those errors appear to be more than just from updates to static analysis tool. They would need to be addressed first before this PR can be merged.
I'll take a look at it later.

**Comment by Xerkus** [comment]
I do not understand why code sniffer invokes fatal error requiring return type will change annotation but it does not fail locally on php 8.2 or via tests

**Comment by Xerkus** [comment]
Hm. That is a LOT of skipped tests

**Comment by Xerkus** [comment]
generic ldap resource changed to dedicated objects starting with php 8.1. Since php 8.1 is now minimum the resource type is no longer valid so phpdoc was updated to reflect that and checks for resource were simplified to look only for relevant classes. 

Missing `ReturnTypeWillChange` annotation indicates that support for php 8.1 and 8.2 was incomplete. It was not previously picked up most likely due to disabled online tests. That would be handled in #48

**Pull request merged**
